import { getBaseUrls } from '@/api/baseUrls';
import axios from '@/utils/request';
import type { FileTree } from '@/types/HWPL/extra/FileTree';

const generatedFileTree = {
  gacha: '/assetsFileList/Assets/Gacha/index.json',
} as const;
export type AvailableFileTreeName = keyof typeof generatedFileTree;

// get file tree pre-generated by backend
export async function getFileTree(name: AvailableFileTreeName): Promise<FileTree> {
  const { staticApiBaseUrl } = getBaseUrls();
  const url = `${staticApiBaseUrl}${generatedFileTree[name]}`;
  const response = await axios.get(url);
  return response.data;
}
