// parse @mdi/font/css/materialdesignicons.css and generate the icons array

import * as path from 'path';
import fs from 'fs';

const src = path.resolve(
  'node_modules',
  '@mdi',
  'font',
  'css',
  'materialdesignicons.css',
);
const dest = path.resolve('src', 'types', 'mdi', 'icons.ts');

const css = fs.readFileSync(src, 'utf8');
const matchArray = css.match(/(mdi-.*)::before/g) || [];
const icons = matchArray.map(icon => icon.replace('::before', ''));
const iconString = icons.map(icon => `'${icon}'`).join(',');
const content = `/* generated by /scripts/generate-mdi-types.ts */
/* preview all icons at: https://materialdesignicons.com/ */

export const icons = [${iconString}] as const;`;
fs.writeFileSync(dest, content);
