#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

. "$(dirname -- "$0")/_/husky.sh"

# check eslint errors
pnpm run lint-staged
# check typescript errors (no longer needed in local, since we have CI)
# pnpm run tsc