name: Test
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.14.0
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lock
      - name: Run lint and tests
        run: pnpm run lint && pnpm run tsc
      - name: Generate Static Websites
        env:
          TZ: Asia/Shanghai
        run: pnpm run build
